# Basic Site Info
title My Portfolio
description Data Science and Engineering Projects

# This is the Magic part that tells Jekyll to look 
# into a folder called _projects and treat them as a group
collections
  projects
    output true  # This lets each project have its own separate page
    permalink projectspath

# Optional If you are using a theme, specify it here
theme jekyll-theme-minimal